Add test_find_links
AnnaLangner/explorer pull request #8
Opened 2020-07-24 14:04 UTC by AnnaLangner

2020-07-28 11:38 UTC, klangner requested changes

2020-07-28 11:38 UTC, klangner commented on script/test.py
> +def print_links(links):
This function is not necessary

2020-07-28 11:38 UTC, klangner commented on script/test.py
> +def test_find_links(driver):
If you want to count number of links then:
  * Use function from the script main.py
  * At the end of the function you should expression like: `assert found_number_of_links == expected_number_of_links`
  * Rename this function to `test_link_count`

2020-07-30 14:03 UTC, klangner requested changes

2020-07-30 14:03 UTC, klangner commented on script/test.py
> +  assert found_number_of_links == expected_number_of_links
It is ok, but more common is to use:
```python
assert found_number_of_links == 87
```

2020-07-30 14:03 UTC, klangner commented on script/test.py
> +  return lists_of_tuples
This function shouldn't return anything.
Remember that function should do only 1 thing. In this case it is doing 2 things:
  * Testing links
  * Returning them

Also this function should have the whole test scenario. It means that it should:
 * Get the page: `driver.get("https://annalangner.github.io/Projekt-1/")`
 * find_links
 * Verify links

And Verify means comparing returned list of links to the `expected` list of links. You need to create this expected value.

2020-07-30 14:03 UTC, klangner commented on script/test.py
> +def test_count_links(links):
This function should be self sufficient. It means that it should:

  * Get the page: driver.get("https://annalangner.github.io/Projekt-1/")
  * find_links
  * Verify number of links

So the parameter here should be a driver not list of links

2020-07-30 14:03 UTC, klangner commented on script/test.py
> +top()
Better name for this function is `main` or `test`

2020-07-31 09:42 UTC, AnnaLangner commented on script/test.py
> +  return lists_of_tuples
I don't understand how to crate expected value? LinksInfo is not the expected value?

2020-07-31 10:02 UTC, klangner commented on script/test.py
> +  return lists_of_tuples
You need to create list of LinkInfo objects. Something like:
```python
expected = [LinkInfo("expected title 1", "expected href"), LinkInfo("expected title 2", "expected href")]
```

2021-04-05 20:36 UTC, merged